### ISSUE TITLE
Multiple domains

### ISSUE THREAD

**Issue by sirspock** [mintproject/mint-server#1]
The server does not allow to use multiple domains. Am I right?
mint-server read the config file. And the domain is fixed
```
    wingsProps.put("domain", this.props.getString("wings.domain"));
```

**Comment by sirspock** [comment]
@varunratnakar

**Comment by IKCAP** [comment]
That domain is the one that mint writes workflows and components to, and is
specified by the configuration file. However we can refer to multiple
domains as far as running existing workflows goes (data generation
workflows)

**Comment by sirspock** [comment]
If I create a new user who doesn't have access to the default domain: 
How can a user use the custom domain?
Can a user register new data into the custom domain?
